services:
  backend:
    image: mlastovsky/movie-repository:1.0.0
    container_name: movie-repository-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/movies_repository
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 128875
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    container_name: movie-repository-db
    environment:
      POSTGRES_DB: movies_repository
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 128875
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - movie-repository-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  movie-repository-db:
